package vn.socialnet.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import vn.socialnet.model.Notification;
import vn.socialnet.model.User;

import java.util.List;

@Repository
public interface NotificationRepository extends JpaRepository<Notification, Long> {

    /**
     * Get all notifications for a user, newest first.
     * Fully auto-generated by JPA.
     */
    List<Notification> findByUserOrderByCreatedAtDesc(User user);

    /**
     * Count unread notifications.
     * Fully auto-generated by JPA.
     */
    Long countByUserIdAndIsReaddedFalse(Long userId);

    /**
     * Mark a specific notification as read.
     * Must use JPQL because Spring Data JPA cannot auto-generate UPDATE queries.
     */
    @Modifying
    @Query("UPDATE notifications  n SET n.isReadded = true " +
            "WHERE n.id = :notificationId AND n.user.id = :userId")
    void markAsRead(Long notificationId, Long userId);

    /**
     * Mark all notifications as read.
     * Must use JPQL.
     */
    @Modifying
    @Query("UPDATE notifications n SET n.isReadded = true " +
            "WHERE n.user.id = :userId AND n.isReadded = false")
    void markAllAsRead(Long userId);
}
